version: "3.8"
services:
  ###
  ### SERVICES
  ###

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    networks:
      - hasuraproject
    environment:
      NODE_ENV: production
      HASURA_ENDPOINT: http://hasura:8080
      HASURA_JWT_SECRET: ${HASURA_JWT_SECRET:-h2leOvdgjwpV0As5L8rZlV3VDVOsOmwk}
    entrypoint: ["npm", "start"]
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://auth:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        REACT_APP_HASURA_URL: ""
    networks:
      - hasuraproject
    ports:
      - "${APP_PORT:-3000}:80"
    environment:
      PROXY_PASS: http://hasura:8080
    depends_on:
      hasura:
        condition: service_healthy

  ###
  ### INFRASTRUCTURE
  ###

  hasura:
    build:
      context: ./services/hasura
    networks:
      - hasuraproject
    depends_on:
      postgres:
        condition: service_healthy
      auth:
        condition: service_healthy
    ports:
      - "${HASURA_PORT:-8080}:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET:-hasura}"
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "${HASURA_JWT_SECRET:-h2leOvdgjwpV0As5L8rZlV3VDVOsOmwk}"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      AUTH_BASE_URL: http://auth:8080
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: always

  postgres:
    build:
      context: ./services/postgres
    networks:
      - hasuraproject
    volumes:
      - ./.docker-data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
    restart: always

networks:
  hasuraproject:
    driver: bridge
